### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by mygnu**
resolves https://github.com/rust-psutil/rust-psutil/issues/95

### CODE REVIEW

**Comment by mygnu** [comment]
Can someone please have a look at this?

**Comment by AaronO** [comment]
@cjbassi Anything blocking this ?

**Comment by orium** [comment]
I'm also blocked on this issue.

**Comment by mike-lloyd03** [comment]
Any way we can get this merged? I may have to drop this crate for Heim.

**Comment by rkday** [comment]
Merged, and I've pushed 3.2.2 at https://crates.io/crates/psutil/3.2.2. Hopefully that works for you, but please reopen this issue or create a new one if it doesn't!

**Pull request merged**
